application: myria-web
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  expiration: "7d"
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: css 
- url: /fonts
  static_dir: fonts 
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

# This must be last
- url: /.*
  script: myria_web_main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
