application: myria-web
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  expiration: "7d"
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /(apple-touch.*\.png)
  expiration: "7d"
  static_files: static/\1
  upload: static/apple.*\.png
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /data
  static_dir: data
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
# This handler must be last
- url: /.*
  script: myria_web_main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
